"""
forensics_compliance.py  —  SAR / CTR Compliance Filing
Generates FinCEN-compatible SAR and CTR XML/PDF for BSA E-Filing.
"""

import xml.etree.ElementTree as ET
from xml.dom.minidom import parseString
from datetime import datetime
from typing import Dict, List, Optional
import hashlib
import io
import streamlit as st
import pandas as pd
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch


# ─────────────────────────────────────────────────────────────
# SAR NARRATIVE BUILDER
# ─────────────────────────────────────────────────────────────

def generate_sar_narrative(
    case_id: str,
    subject_addresses: List[str],
    total_volume: float,
    typologies: List[str],
    findings_summary: str,
    investigator: str = "Crypto Forensics Analyzer",
    filing_institution: str = "",
    recommendation: str = "SAR FILING RECOMMENDED",
) -> str:
    """
    Generate a FinCEN-compliant SAR narrative paragraph.
    Follows BSA E-Filing guidance for virtual currency SARs.
    """
    date_str = datetime.now().strftime("%B %d, %Y")
    addr_list = "\n".join(f"  • {a}" for a in subject_addresses[:20])
    typo_list = "\n".join(f"  • {t}" for t in typologies)

    return f"""SUSPICIOUS ACTIVITY REPORT NARRATIVE
Case ID: {case_id}
Filing Date: {date_str}
Filing Institution: {filing_institution or "See filing institution details"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PART I — SUMMARY OF SUSPICIOUS ACTIVITY

On {date_str}, {filing_institution or "the reporting institution"} identified suspicious
virtual currency activity involving the following blockchain addresses:

{addr_list}

Total transaction volume associated with this activity: ${total_volume:,.2f}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PART II — DESCRIPTION OF SUSPICIOUS ACTIVITY

{findings_summary}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PART III — TYPOLOGIES IDENTIFIED

The following suspicious activity typologies were identified consistent with
FATF and FinCEN guidance on virtual currency money laundering:

{typo_list}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PART IV — DISPOSITION

Recommended action: {recommendation}

This report was generated by: {investigator}
Report generated: {datetime.now().isoformat()}

NOTE: This SAR narrative requires review and signature by a BSA Officer
before submission to FinCEN BSA E-Filing System (https://bsaefiling.fincen.treas.gov).
Virtual currency SARs should be filed within 30 days of initial detection
(or 60 days if no suspect is identified).
""".strip()


def generate_sar_xml(
    case_id: str,
    filing_institution: str,
    ein: str,
    subject_addresses: List[str],
    total_volume: float,
    narrative: str,
    activity_date_start: str,
    activity_date_end: str,
) -> str:
    """
    Generate FinCEN SAR XML in BSA E-Filing format.
    Schema: FinCEN CTR/SAR XML v2.0 (simplified — real filing requires
    FinCEN-issued credentials and the full schema).
    """
    root = ET.Element("FinCEN_SAR", {
        "xmlns": "FinCEN/SAR/2.0",
        "version": "2.0",
        "created": datetime.now().isoformat(),
    })

    # Filing institution
    filer = ET.SubElement(root, "FilingInstitution")
    ET.SubElement(filer, "Name").text = filing_institution
    ET.SubElement(filer, "EIN").text = ein
    ET.SubElement(filer, "FilingDate").text = datetime.now().strftime("%Y%m%d")

    # Activity
    activity = ET.SubElement(root, "SuspiciousActivity")
    ET.SubElement(activity, "CaseID").text = case_id
    ET.SubElement(activity, "ActivityDateFrom").text = activity_date_start
    ET.SubElement(activity, "ActivityDateTo").text = activity_date_end
    ET.SubElement(activity, "TotalAmount").text = f"{total_volume:.2f}"
    ET.SubElement(activity, "Currency").text = "USD"
    ET.SubElement(activity, "VirtualCurrencyInvolved").text = "Y"

    # Subject addresses
    subjects = ET.SubElement(activity, "Subjects")
    for addr in subject_addresses[:10]:
        subj = ET.SubElement(subjects, "Subject")
        ET.SubElement(subj, "VirtualCurrencyAddress").text = addr
        ET.SubElement(subj, "AddressType").text = (
            "TRON" if addr.startswith("T") and len(addr) == 34 else
            "BITCOIN" if addr.startswith(("1","3","bc1")) else "EVM"
        )

    # Narrative
    ET.SubElement(activity, "Narrative").text = narrative

    # Indicators
    indicators = ET.SubElement(activity, "SuspiciousActivityIndicators")
    ET.SubElement(indicators, "VirtualCurrencyTransaction").text = "Y"
    ET.SubElement(indicators, "RapidMovementOfFunds").text = "Y"

    pretty = parseString(ET.tostring(root, encoding="unicode")).toprettyxml(indent="  ")
    return pretty


def generate_ctr_data(
    filer_name: str,
    filer_ein: str,
    transactions: List[Dict],
) -> Dict:
    """
    Generate Currency Transaction Report (CTR) data.
    Required for cash/crypto transactions ≥ $10,000.
    """
    total = sum(t.get("amount", 0) for t in transactions)
    return {
        "form_type":    "FinCEN CTR (Form 112)",
        "filing_date":  datetime.now().strftime("%Y-%m-%d"),
        "filer":        filer_name,
        "ein":          filer_ein,
        "total_amount": total,
        "tx_count":     len(transactions),
        "exceeds_threshold": total >= 10_000,
        "transactions": transactions[:25],
        "note": "CTR must be filed within 15 days of transaction via BSA E-Filing.",
    }


def generate_sar_pdf(
    narrative: str,
    case_id: str,
    subject_addresses: List[str],
    total_volume: float,
    filing_institution: str,
) -> io.BytesIO:
    """Generate a formatted SAR PDF document."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter,
                             topMargin=0.75*inch, bottomMargin=0.75*inch,
                             leftMargin=0.75*inch, rightMargin=0.75*inch)
    S = getSampleStyleSheet()
    tit  = ParagraphStyle("T", parent=S["Title"],   fontSize=14, spaceAfter=4)
    h1   = ParagraphStyle("H", parent=S["Heading1"],fontSize=11, spaceBefore=10)
    body = ParagraphStyle("B", parent=S["Normal"],   fontSize=8,  leading=13)
    code = ParagraphStyle("C", parent=S["Code"],     fontSize=7,  leading=10, fontName="Courier")
    warn = ParagraphStyle("W", parent=S["Normal"],   fontSize=8,  textColor=colors.HexColor("#ff4444"))

    elems = []
    elems.append(Paragraph("SUSPICIOUS ACTIVITY REPORT (SAR)", tit))
    elems.append(Paragraph(
        f"Case: {case_id}  |  Date: {datetime.now().strftime('%Y-%m-%d')}  |  "
        f"Filing Institution: {filing_institution or 'N/A'}",
        ParagraphStyle("sub", parent=S["Normal"], fontSize=8, textColor=colors.grey)
    ))
    elems.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#ff4444"), spaceAfter=8))

    elems.append(Paragraph("⚠️ DRAFT — REQUIRES BSA OFFICER REVIEW BEFORE SUBMISSION", warn))
    elems.append(Spacer(1, 6))

    # Summary table
    data = [["Field", "Value"],
            ["Case ID", case_id],
            ["Filing Date", datetime.now().strftime("%Y-%m-%d")],
            ["Total Volume", f"${total_volume:,.2f}"],
            ["Addresses", str(len(subject_addresses))],
            ["Disposition", "SAR FILING RECOMMENDED"]]
    t = Table(data, colWidths=[2*inch, 4*inch])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1e1e2e")),
        ("TEXTCOLOR",  (0,0), (-1,0), colors.white),
        ("FONTNAME",   (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE",   (0,0), (-1,-1), 8),
        ("GRID",       (0,0), (-1,-1), 0.4, colors.grey),
        ("LEFTPADDING",(0,0), (-1,-1), 6),
        ("TOPPADDING", (0,0), (-1,-1), 3),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.HexColor("#f5f5f5"), colors.white]),
    ]))
    elems.append(t); elems.append(Spacer(1, 10))

    elems.append(Paragraph("Subject Addresses", h1))
    for addr in subject_addresses[:15]:
        elems.append(Paragraph(addr, code))

    elems.append(Paragraph("SAR Narrative", h1))
    for para in narrative.split("\n"):
        if para.strip():
            elems.append(Paragraph(para.strip(), body))
            elems.append(Spacer(1, 2))

    elems.append(Spacer(1, 16))
    elems.append(HRFlowable(width="100%", thickness=1))
    elems.append(Paragraph(
        "CONFIDENTIAL — BSA SAR INFORMATION — DO NOT DISCLOSE  |  "
        "File via: https://bsaefiling.fincen.treas.gov",
        ParagraphStyle("f", parent=S["Normal"], fontSize=7, textColor=colors.grey)
    ))

    doc.build(elems)
    buf.seek(0)
    return buf


def render_compliance_ui(df: Optional[pd.DataFrame] = None):
    """Full SAR/CTR compliance filing UI."""
    st.markdown("### ⚖️ SAR / CTR Compliance Filing")
    st.caption("Generate FinCEN-compliant Suspicious Activity Reports and Currency Transaction Reports.")

    comp_tab1, comp_tab2, comp_tab3 = st.tabs(["📋 SAR Generator", "💵 CTR Generator", "📖 Guidance"])

    with comp_tab1:
        st.markdown("**SAR — Suspicious Activity Report**")
        c1, c2 = st.columns(2)
        with c1:
            case_id      = st.text_input("Case ID", value=f"CASE-{datetime.now().strftime('%Y%m%d')}-001")
            filing_inst  = st.text_input("Filing Institution Name")
            ein          = st.text_input("EIN / Tax ID", placeholder="XX-XXXXXXX")
            investigator = st.text_input("Investigator Name")
        with c2:
            date_from = st.date_input("Activity Date From")
            date_to   = st.date_input("Activity Date To")
            total_vol = st.number_input("Total Volume ($)", min_value=0.0, step=1000.0,
                                         value=float(df["amount"].sum()) if df is not None else 0.0)
            recommendation = st.selectbox("Recommended Action", [
                "SAR FILING RECOMMENDED", "CONTINUE MONITORING",
                "LAW ENFORCEMENT REFERRAL", "ACCOUNT CLOSURE"
            ])

        # Subject addresses
        st.markdown("**Subject Addresses** (one per line)")
        default_addrs = "\n".join(df["from_address"].value_counts().head(5).index.tolist()) if df is not None else ""
        addr_text = st.text_area("Addresses", value=default_addrs, height=100)
        subject_addrs = [a.strip() for a in addr_text.split("\n") if a.strip()]

        # Typologies
        st.markdown("**Detected Typologies**")
        typo_options = [
            "Structuring / Smurfing (FATF #3)",
            "Layering via mixing service (FATF #8)",
            "Cross-chain bridge layering",
            "Peeling chain (ransomware cashout pattern)",
            "Rapid fund movement (<1 hour TTF)",
            "Round-number transfers",
            "Use of sanctioned address (OFAC SDN)",
            "Darknet marketplace interaction",
            "Circular flow / wash trading",
            "Coordinated wallet cluster activity",
        ]
        selected_typos = st.multiselect("Select applicable typologies", typo_options)

        # Narrative
        custom_narrative = st.text_area("Additional narrative details", height=120,
                                         placeholder="Describe the suspicious activity in your own words…")
        findings_summary = custom_narrative or (
            f"Analysis of {len(df):,} blockchain transactions identified patterns "
            f"consistent with money laundering activity across {df['chain'].nunique() if df is not None else 'multiple'} chains."
            if df is not None else "See attached transaction analysis."
        )

        if st.button("📋 Generate SAR", type="primary"):
            narrative = generate_sar_narrative(
                case_id=case_id, subject_addresses=subject_addrs,
                total_volume=total_vol, typologies=selected_typos or ["Under investigation"],
                findings_summary=findings_summary, investigator=investigator,
                filing_institution=filing_inst, recommendation=recommendation,
            )
            st.session_state.sar_narrative = narrative
            st.session_state.sar_meta = {
                "case_id": case_id, "filing_inst": filing_inst, "ein": ein,
                "subject_addrs": subject_addrs, "total_vol": total_vol,
                "date_from": str(date_from), "date_to": str(date_to),
            }
            st.success("SAR generated ✅")

        if "sar_narrative" in st.session_state:
            st.text_area("SAR Narrative (review before filing)", st.session_state.sar_narrative, height=300)
            meta = st.session_state.sar_meta

            dl1, dl2, dl3 = st.columns(3)
            with dl1:
                st.download_button("📄 Download Narrative (.txt)",
                    st.session_state.sar_narrative.encode(),
                    f"SAR_narrative_{meta['case_id']}.txt", "text/plain")
            with dl2:
                xml_str = generate_sar_xml(
                    case_id=meta["case_id"], filing_institution=meta["filing_inst"],
                    ein=meta["ein"], subject_addresses=meta["subject_addrs"],
                    total_volume=meta["total_vol"], narrative=st.session_state.sar_narrative,
                    activity_date_start=meta["date_from"], activity_date_end=meta["date_to"],
                )
                st.download_button("📋 Download XML (BSA E-Filing)",
                    xml_str.encode(), f"SAR_{meta['case_id']}.xml", "application/xml")
            with dl3:
                pdf_buf = generate_sar_pdf(
                    narrative=st.session_state.sar_narrative,
                    case_id=meta["case_id"], subject_addresses=meta["subject_addrs"],
                    total_volume=meta["total_vol"], filing_institution=meta["filing_inst"],
                )
                st.download_button("📥 Download PDF",
                    pdf_buf.getvalue(), f"SAR_{meta['case_id']}.pdf", "application/pdf",
                    type="primary")

    with comp_tab2:
        st.markdown("**CTR — Currency Transaction Report (Form 112)**")
        st.caption("Required for cash/crypto transactions ≥ $10,000 in a single business day.")
        ctr_filer = st.text_input("Filer Name", key="ctr_filer")
        ctr_ein   = st.text_input("EIN", key="ctr_ein", placeholder="XX-XXXXXXX")
        if df is not None:
            large_txs = df[df["amount"] >= 10_000].head(25)
            if not large_txs.empty:
                st.warning(f"⚠️ {len(large_txs)} transactions ≥ $10,000 detected — CTR may be required")
                st.dataframe(large_txs[["date","from_address","to_address","amount","token"]],
                             width='stretch', hide_index=True)
                if st.button("📋 Generate CTR Data", key="gen_ctr"):
                    ctr = generate_ctr_data(ctr_filer, ctr_ein,
                                             large_txs.to_dict("records"))
                    st.json(ctr)
            else:
                st.info("No transactions ≥ $10,000 in current dataset.")
        else:
            st.info("Load a dataset to generate CTR data.")

    with comp_tab3:
        st.markdown("""
**SAR Filing Requirements**
- File within **30 days** of detecting suspicious activity
- **60 days** if no suspect is identified
- File via: [FinCEN BSA E-Filing](https://bsaefiling.fincen.treas.gov)
- Do NOT notify the subject ("tipping off" prohibition — 31 USC 5318(g)(2))

**CTR Requirements**
- File within **15 days** of transaction
- Required for transactions **≥ $10,000** (cash or crypto equivalent)
- Multiple transactions that aggregate to $10,000+ in one day also trigger CTR

**Virtual Currency Guidance**
- FIN-2019-G001: FinCEN guidance on virtual currency businesses
- FATF R.15: Virtual asset service providers
- SAR field code `35q` for virtual currency transactions

**Disclaimer**: This tool generates draft SAR/CTR documents for review.
All filings require review and signature by a qualified BSA Compliance Officer.
""")
